name: mbjg
type: craftcms
docroot: backend/web
php_version: "8.5"
nodejs_version: "24"
webserver_type: nginx-fpm
composer_root: backend
xdebug_enabled: false
additional_hostnames:
  - admin.mbjg
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
hooks:
  post-stop:
    - exec-host: make purge
  pre-start:
    - exec-host: make env
upload_dirs:
  - uploads
web_extra_exposed_ports:
  - name: astro
    container_port: 4321
    http_port: 4321
    https_port: 4322
web_environment:
  - VIRTUAL_HOST=admin.mbjg.ddev.site,mbjg.ddev.site
  - CRAFT_CMD_ROOT=/var/www/html/backend
web_extra_daemons:
  - name: "astro"
    command: "cd /var/www/html/frontend && npm run dev -- --host"
    directory: "/var/www/html/frontend"
